on: [push]
name: action for python

jobs:
    build:
        name: build python tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: test run
              run: python -m unittest test.py